Update node configuration
palomachain/paloma-docs pull request #5
Opened 2022-07-28 20:57 UTC by DannyS03

- tests guides end-to-end for node and val content
- updates configuration steps

2022-07-29 21:11 UTC, verabehr requested changes
small change request

2022-07-29 21:11 UTC, verabehr commented on docs/src/guide/maintain/node/build-paloma-core.md
> +- Open `~/.testnet/paloma-testnet-6/app.toml`.
this needs to stay `~/.paloma/config/app.toml

2022-07-30 01:40 UTC, DannyS03 commented on docs/src/guide/maintain/node/build-paloma-core.md
> +- Open `~/.testnet/paloma-testnet-6/app.toml`.
addressed

2022-08-03 18:38 UTC, verabehr approved these changes
lg

2022-08-03 18:49 UTC, merged