Remove localpaloma configurations
palomachain/paloma-docs pull request #6
Opened 2022-07-29 18:55 UTC by DannyS03

localpaloma not yet available to use (containerized version of network)

2022-07-29 20:05 UTC, verabehr requested changes
I didn't go through all lines as it seems to be the same issue throughout. Please refer to the first few comments, but it applies to teh whole PR

2022-07-29 20:05 UTC, verabehr commented on docs/src/guide/develop/palomain/initial-setup.md
> +paloma-testnet-6 is a development environment designed to make it easy for smart contract developers to test their contracts locally. palomain can also interact with the Paloma blockchain's live test
same comments as above. Also palomain and pisco don't exist on paloma

2022-07-29 20:05 UTC, verabehr commented on docs/src/guide/develop/palomain/using-palomain-localpaloma.md
same comment as above

2022-08-03 18:55 UTC, verabehr reviewed
putting this on hold until we re-review and paloma.js is ready for use.

2022-08-04 00:38 UTC, DannyS03 commented
@verabehr this was the PR that showcases the SDK docs: https://github.com/palomachain/paloma-docs/pull/7, while this one is mainly removing localpaloma

2022-08-06 04:40 UTC, merged