Re-add tools guide
palomachain/paloma-docs pull request #8
Opened 2022-07-29 19:01 UTC by DannyS03

showcase tools guide with updated references

2022-08-03 18:57 UTC, verabehr requested changes
small change request

2022-08-03 18:57 UTC, verabehr commented on docs/src/guide/develop/quick-start/which-tools.md
please add that this is a community project

2022-08-03 18:57 UTC, verabehr commented on docs/src/guide/develop/quick-start/which-tools.md
> +Follow the [Wallet Provider tutorial](../wallet-provider/wallet-provider-tutorial.md) to get started.
please remove paloma.py and wallet for now

2022-08-04 00:36 UTC, DannyS03 commented on docs/src/guide/develop/quick-start/which-tools.md
addressed

2022-08-04 00:36 UTC, DannyS03 commented on docs/src/guide/develop/quick-start/which-tools.md
> +Follow the [Wallet Provider tutorial](../wallet-provider/wallet-provider-tutorial.md) to get started.
addressed

2022-08-06 05:00 UTC, merged